package com.example.DosifyProject.model;

import com.example.DosifyProject.Enum.VaccineType;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.FieldDefaults;
import org.hibernate.annotations.CreationTimestamp;

import java.util.Date;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@FieldDefaults(level = AccessLevel.PRIVATE)
@Table(name = "dose1")
public class Dose1 {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    Integer Id;

    @Column(name = "dose_id")
    String doseId; // generated by uuid

    @Enumerated(EnumType.STRING)
    @Column(name = "vaccine_type")
    VaccineType vaccineType;

    @CreationTimestamp
    @Column(name = "vaccination_date")
    Date date;

}
